### PR TITLE
Remove workaround for missing 'models' in Swagger 1.x

### PR DESCRIPTION
**Pull request by IvanGoncharov**

### CODE REVIEW

**Comment by bobby-brennan** [comment]
Does the new swagger-converter address this issue?

**Comment by IvanGoncharov** [comment]
Yes by this
https://github.com/apigee-127/swagger-converter/pull/22

**Comment by IvanGoncharov** [comment]
Do you have test samples for other workarounds in the same function?
It's good idea to this the rest of them.

**Comment by IvanGoncharov** [comment]
@bobby-brennan Ping

**Pull request merged**
