### PR TITLE
Expose 'ResourceReaders'.

### PR DESCRIPTION
**Pull request by IvanGoncharov**
Allow to override how URLs and files are read.

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
@bobby-brennan Can you please review it?

**Comment by IvanGoncharov** [comment]
@bobby-brennan This PR blocks me.
So I will merge it, but please review it.

**Comment by bobby-brennan** [comment]
Where else do you need this? Maybe it should be factored out? It seems unrelated to converting API specs

**Comment by IvanGoncharov** [comment]
@bobby-brennan It's kind of related.
If I need to customize how HTTP request is done.
For example, add retry which is my use case.
You can download spec on your own and just pass in lib.
But this lib also resolves external references, and I don't have any control over it.

I think lib should provide some default readers which satisfy majority of use cases.
But still allow supplying your own in case if you try to do something unusual.

**Comment by IvanGoncharov** [comment]
@bobby-brennan I this case I tried to reuse the same lib which I use for all my projects: https://github.com/APIs-guru/makeRequest/blob/master/index.js

It's just a workaround for crappy internet connection.
In a nutshell, it retries connection up to 3 times.

**Comment by bobby-brennan** [comment]
Got it, sounds good!

Bobby Brennan
bobby.brennan@gmail.com

**Pull request merged**
