### PR TITLE
Fix variable names.

### PR DESCRIPTION
**Pull request by IvanGoncharov**
It fix for #6 PR
I will create test cases negative test cases, to catch such errors in future.

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
IMHO [strict mode](http://www.w3schools.com/js/js_strict.asp) really helps to prevent such mistakes.
It makes JS more "safe", I personally use it in all my projects.
If you agree, I can make one PR for all files.

**Comment by bobby-brennan** [comment]
SGTM. FYI it looks like https://www.npmjs.com/package/strict-mode might
help.

I've been learning node on the fly, so all this is super helpful. Thanks
for the pointers!

Bobby Brennan
bobby.brennan@gmail.com

**Comment by IvanGoncharov** [comment]
I'm also C/C++ programmer, specialized in network equipment(firmware for switches/routers).
And have only couple of months experience with JS, so you should check all my suggestion :)

**Comment by IvanGoncharov** [comment]
By the way, "strict mode" + "lodash" makes JS very similar to Python.
Which is by far my favorite language, and that explains my "code style" :smile:

**Comment by IvanGoncharov** [comment]
I read about `strict-mode` package and IMHO it's looks to invasive.
It force `strict mode` for all npm packages that you use.
You can work around with clever tricks, see this [issue](https://github.com/fibo/strict-mode/issues/1)
But I think it's to high price for saving one line per file.

**Pull request merged**
